"""Второй демонстрационный сценарий: рабочий конфликт внутри команды."""
from app.models.scenario import Scenario

TEAM_CONFLICT_SCENARIO = Scenario(
    id="sc_team_conflict_v1",
    title="Конфликт в команде: сроки, ответственность и доверие",
    description=(
        "Коллега регулярно меняет договорённости по задаче, из-за чего сдвигаются сроки релиза. "
        "Нужно провести прямой разговор без обвинений, понять интересы обеих сторон и договориться "
        "о прозрачном правиле работы. Если прямой разговор не сработает, допустима нейтральная эскалация."
    ),
    difficulty="medium",
    industry="team",
    modes=["text", "voice"],
    goal="Восстановить рабочее взаимодействие: согласовать правило изменений, владельца, канал уведомления и дату проверки",
    user_role="Коллега или тимлид, которому нужно восстановить рабочую договорённость",
    constraints=[
        "обсуждать наблюдаемые эпизоды, а не личность коллеги",
        "не использовать формулировки «ты всегда» и «ты никогда»",
        "не требовать наказания как единственного решения",
        "учесть интересы, ограничения и нагрузку второй стороны",
        "закончить разговор проверяемой договорённостью",
    ],
    opponent={
        "role": "Коллега из смежной команды, который защищает свой процесс и считает претензии преувеличенными",
        "style": "защитный, рациональный, иногда раздражённый; готов сотрудничать, если разговор опирается на факты",
        "tone": "деловой, напряжённый, но уважительный",
    },
    assistant={
        "role": "Коуч по сложным рабочим разговорам",
        "style": "помогает отделять факт от интерпретации, находить интересы и превращать конфликт в правило процесса",
        "tone": "спокойный и конкретный",
    },
    interest={"start": 50, "min": 0, "max": 100},
    max_adjust=15,
    scenario_type="curated",
    tags=["конфликт", "команда", "обратная связь", "эскалация", "Harvard", "SPIN"],
    knowledge_refs=['spin-question-sequence'],
    coach_profile={
        "focus": ["факты вместо ярлыков", "интересы обеих сторон", "процессная договорённость"],
        "default_hint": "Возвращай разговор от обвинения к эпизоду, влиянию, интересам и наблюдаемому правилу.",
    },
    published=True,
    graph={
        "nodes": [
            {
                "id": "start", "type": "start", "label": "Открытие сложного разговора",
                "description": "Коллега готов выслушать, но ожидает обвинения и заранее защищает свой процесс.",
                "prompt_hint": "Я могу уделить этому разговору немного времени. Что именно произошло?",
                "knowledge_refs": [],
                "coach_hint": "Сначала задай рамку совместного решения и назови конкретный эпизод без оценки личности.",
                "coach_focus": ["рамка", "факт", "безопасный тон"],
                "watch_for": ["конкретная дата или задача", "совместный результат"],
                "avoid": ["ты всегда", "ты никогда", "обвинение в безответственности"],
            },
            {
                "id": "facts", "type": "phase", "label": "Факты эпизода",
                "description": "Нужно описать наблюдаемый сдвиг договорённости: что было согласовано, что изменилось и когда.",
                "interest_delta": 5,
                "knowledge_refs": [],
                "coach_hint": "Попроси участника описать один эпизод по схеме: договорённость → изменение → рабочее последствие.",
                "coach_focus": ["наблюдаемый факт", "последствие"],
                "watch_for": ["один эпизод", "срок или артефакт", "влияние на работу"],
                "avoid": ["обобщения", "диагнозы личности"],
            },
            {
                "id": "interests", "type": "phase", "label": "Интересы и ограничения",
                "description": "Коллега объясняет, что его команда меняет сроки из-за срочных запросов и нехватки информации.",
                "interest_delta": 7,
                "knowledge_refs": ['spin-question-sequence'],
                "coach_hint": "Переведи защитную позицию коллеги в интерес: скорость реакции, качество входных данных, снижение риска.",
                "coach_focus": ["интересы", "SPIN-вопросы"],
                "watch_for": ["открытый вопрос", "перефразирование", "интерес коллеги"],
                "avoid": ["сразу доказывать свою правоту"],
            },
            {
                "id": "impact", "type": "phase", "label": "Цена бездействия",
                "description": "Стороны сопоставляют последствия текущей модели: срыв релиза, переработки, потеря доверия или ошибки.",
                "interest_delta": 4,
                "knowledge_refs": ['spin-question-sequence'],
                "coach_hint": "Задай вопрос о последствиях, но не преувеличивай их; свяжи проблему с общим результатом команды.",
                "coach_focus": ["последствия", "общий результат"],
                "watch_for": ["срок", "качество", "стоимость повторной работы"],
                "avoid": ["катастрофизация", "шантаж руководителем"],
            },
            {
                "id": "options", "type": "phase", "label": "Варианты процесса",
                "description": "Нужно предложить не единственное требование, а несколько рабочих способов менять договорённости.",
                "interest_delta": 7,
                "knowledge_refs": [],
                "coach_hint": "Собери варианты: фиксированное окно изменений, быстрый канал уведомления или правило приоритизации.",
                "coach_focus": ["варианты", "критерии", "взаимная выгода"],
                "watch_for": ["2–3 варианта", "плюсы и ограничения каждого"],
                "avoid": ["требование подчиниться", "решение без учёта нагрузки"],
            },
            {
                "id": "role_split", "type": "phase", "label": "Роли и ответственность",
                "description": "Уточняется, кто принимает решение о смене приоритета, кто уведомляет и где фиксируется новая дата.",
                "interest_delta": 8,
                "knowledge_refs": [],
                "coach_hint": "Добейся операциональности: владелец решения, канал, формат сообщения и критерий срочности.",
                "coach_focus": ["владелец", "критерий", "канал"],
                "watch_for": ["кто", "где", "когда", "по какому критерию"],
                "avoid": ["размытая ответственность"],
            },
            {
                "id": "protocol", "type": "phase", "label": "Протокол изменений",
                "description": "Стороны проверяют конкретное правило: как действовать, если срочная задача появляется после фиксации плана.",
                "interest_delta": 7,
                "knowledge_refs": [],
                "coach_hint": "Попроси проиграть один будущий пример и проверить, действительно ли правило сработает под нагрузкой.",
                "coach_focus": ["проверяемость", "исключения", "будущий пример"],
                "watch_for": ["сценарий исключения", "порог срочности", "новый срок"],
                "avoid": ["правило только для идеальных условий"],
            },
            {
                "id": "escalation", "type": "phase", "label": "Нейтральная эскалация",
                "description": "Если прямой разговор не снимает риск, участник формулирует запрос руководителю как проблему процесса с вариантами решения.",
                "interest_delta": -2,
                "knowledge_refs": [],
                "coach_hint": "Эскалируй не человека, а процесс: факты, влияние, уже предпринятые шаги и два варианта решения.",
                "coach_focus": ["факты", "варианты", "нейтральный запрос"],
                "watch_for": ["история попыток", "риск проекту", "запрос на решение"],
                "avoid": ["публичная жалоба", "требование наказания"],
            },
            {
                "id": "commitment", "type": "phase", "label": "Фиксация договорённости",
                "description": "Нужно повторить новое правило, владельца, канал и срок проверки, чтобы разговор не остался обещанием.",
                "interest_delta": 10,
                "knowledge_refs": [],
                "coach_hint": "Проверь договорённость по чек-листу и предложи короткую дату проверки результата.",
                "coach_focus": ["закрытие", "проверка"],
                "watch_for": ["правило", "владелец", "дата проверки"],
                "avoid": ["давай просто лучше общаться"],
            },
            {
                "id": "success", "type": "end", "label": "Рабочая договорённость восстановлена",
                "description": "Стороны согласовали правило изменений, роли, канал уведомления и дату проверки.",
                "outcome": "success",
            },
            {
                "id": "success_repair", "type": "end", "label": "Согласована проверка после эскалации",
                "description": "Проблема передана руководителю нейтрально, выбрано решение и назначен контрольный срок.",
                "outcome": "success",
            },
            {
                "id": "failure", "type": "end", "label": "Конфликт обострён",
                "description": "Ультиматум, личное обвинение или отказ от фактов сделали рабочий контакт невозможным.",
                "outcome": "failure",
            },
        ],
        "edges": [
            {"from": "start", "to": "facts", "trigger": {"type": "intent", "value": "describe_incident"}},
            {"from": "start", "to": "interests", "trigger": {"type": "intent", "value": "ask_perspective"}},
            {"from": "start", "to": "failure", "trigger": {"type": "intent", "value": "attack_person"}},
            {"from": "facts", "to": "interests", "trigger": {"type": "intent", "value": "ask_perspective"}},
            {"from": "facts", "to": "impact", "trigger": {"type": "intent", "value": "explain_impact"}},
            {"from": "facts", "to": "escalation", "trigger": {"type": "intent", "value": "ask_manager"}},
            {"from": "interests", "to": "impact", "trigger": {"type": "intent", "value": "explore_consequences"}},
            {"from": "interests", "to": "options", "trigger": {"type": "intent", "value": "propose_options"}},
            {"from": "interests", "to": "failure", "trigger": {"type": "intent", "value": "dismiss_concerns"}},
            {"from": "impact", "to": "options", "trigger": {"type": "intent", "value": "propose_options"}},
            {"from": "impact", "to": "role_split", "trigger": {"type": "intent", "value": "clarify_responsibility"}},
            {"from": "impact", "to": "failure", "trigger": {"type": "intent", "value": "threaten"}},
            {"from": "options", "to": "role_split", "trigger": {"type": "intent", "value": "clarify_responsibility"}},
            {"from": "options", "to": "protocol", "trigger": {"type": "intent", "value": "agree_process"}},
            {"from": "options", "to": "failure", "trigger": {"type": "intent", "value": "impose_solution"}},
            {"from": "role_split", "to": "protocol", "trigger": {"type": "intent", "value": "agree_process"}},
            {"from": "role_split", "to": "options", "trigger": {"type": "intent", "value": "negotiate_terms"}},
            {"from": "role_split", "to": "escalation", "trigger": {"type": "intent", "value": "ask_manager"}},
            {"from": "protocol", "to": "commitment", "trigger": {"type": "intent", "value": "confirm_rule"}},
            {"from": "protocol", "to": "options", "trigger": {"type": "intent", "value": "refine_rule"}},
            {"from": "protocol", "to": "failure", "trigger": {"type": "intent", "value": "refuse"}},
            {"from": "escalation", "to": "options", "trigger": {"type": "intent", "value": "propose_options"}},
            {"from": "escalation", "to": "commitment", "trigger": {"type": "intent", "value": "confirm_rule"}},
            {"from": "escalation", "to": "failure", "trigger": {"type": "intent", "value": "blame_colleague"}},
            {"from": "commitment", "to": "success", "trigger": {"type": "intent", "value": "confirm_agreement"}},
            {"from": "commitment", "to": "success_repair", "trigger": {"type": "intent", "value": "confirm_escalation_plan"}},
            {"from": "commitment", "to": "protocol", "trigger": {"type": "intent", "value": "clarify_terms"}},
            {"from": "commitment", "to": "failure", "trigger": {"type": "intent", "value": "threaten"}},
        ],
    },
)
